# Generated by Django 5.0.14 on 2026-08-21 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userlogin',
            new_name='login',
        ),
    ]
