# Generated by Django 5.0.14 on 2026-08-21 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_userlogin_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logininfo',
            old_name='email',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='logininfo',
            name='name',
        ),
    ]
