# Generated by Django 5.0.14 on 2026-08-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_email_logininfo_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='email',
            new_name='username',
        ),
        migrations.AddField(
            model_name='login',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='number',
            field=models.CharField(default=12345678, max_length=15),
            preserve_default=False,
        ),
    ]
