# Generated by Django 5.0.14 on 2026-08-23 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_email_login_username_login_confirm_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='usertype',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='detections/%Y/%m/%d/')),
                ('prediction', models.CharField(choices=[('Mask', 'Mask'), ('No Mask', 'No Mask')], max_length=10)),
                ('confidence', models.FloatField()),
                ('inference_time_ms', models.PositiveIntegerField()),
                ('source', models.CharField(default='upload', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='mainapp.logininfo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
